### ISSUE TITLE
Add vertical guide lines to patterns.

### ISSUE THREAD

**Issue by sanpilou** [Shelagh-Lewins/twisted-threads-2#54]
See https://www.facebook.com/groups/twistedthreadsapp/posts/6448222121932518/ for an explanation and visual representation.

**Comment by Shelagh-Lewins** [comment]
Adding info from the Facebook post as it may not be visible by the time I get on to this...
![guidelines](https://github.com/Shelagh-Lewins/twisted-threads-2/assets/15693742/3f59c44b-a395-45ff-b046-7357d81398a5)
Good day. I have a feature request. I would like it if it were possible to add a vertical guide lines to the interactive weaving pattern (and the printable pattern too, though I rarely print patterns).

I have added a screenshot with what I have in mind. This would be a very useful feature for me since I like to work with guides, especially when I weave with complicated patterns like 3/1 twill. This way, at a glace, I'd be able to know in my line where my middle is and have a visual separation for every X amount of cards (in this case 4). It's very similar to what Claudia Wollny does in her tablet weaving books and I find it extremly useful, especially when troubleshooting and fixing errors in my weave.
Either be able to tag individual tablets or to have a guide every X number of tablets (so the guide would be between two tablets like the blue dotted lines in my example).

**Comment by Shelagh-Lewins** [comment]
Feature added in https://github.com/Shelagh-Lewins/twisted-threads-2/tree/release_2_2_5
